export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGOUT = 'USER_LOGOUT';

export const EXERCISE_EVENT_CREATED = 'EXERCISE_EVENT_CREATED';
export const EXERCISE_EVENT_UPDATED = 'EXERCISE_EVENT_UPDATED';
export const EXERCISE_EVENT_DELETED = 'EXERCISE_EVENT_DELETED';

export const GOT_EXERCISES = 'GOT_EXERCISES';
