export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGOUT = 'USER_LOGOUT';

export const EXERCISE_EVENT_CREATED = 'EXERCISE_EVENT_CREATED';

export const GOT_EXERCISES = 'GOT_EXERCISES';
